version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang

    working_directory: /go/src/github.com/mariusbreivik/GoNetatmo
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      # Normally, this step would be in a custom primary image;
      # we've added it here for the sake of explanation.
      - run: dep ensure
      #- run: go get github.com/lib/pq
      #- run: go get github.com/mattes/migrate
      #- run: go get github.com/jstemmer/go-junit-report